#!/bin/bash

# create new session
tmux new-session -s practical_programming -x $(tput cols) -y $(tput lines) -n editor -d

# cd to repository folder
tmux send-keys -t practical_programming 'cd ~/Documents/repositories/practical-programming-exercises' C-m

# split window
tmux split-window -v -p 35 -t practical_programming

# cd to repository folder in the 2nd pane
tmux send-keys -t practical_programming:1.2 'cd ~/Documents/repositories/practical-programming-exercises' C-m

# clear screen
tmux send-keys -t practical_programming:1.2 'clear' C-m

# call ls
tmux send-keys -t practical_programming:1.2 'ls' C-m

# select upper pane
tmux select-pane -U -t practical_programming

# clear screen
tmux send-keys -t practical_programming:1.1 'clear' C-m

# call python interpreter
tmux send-keys -t practical_programming:1.1 'python' C-m

# attach session
tmux attach -t practical_programming
